modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "origins_plus_plus"
version = "${version}"
displayName = "Origins++"
description = "A collection of more than 100 origins to fully expand the origins experience."

displayURL = "https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus"
issueTrackerURL = "https://github.com/QuantumXenon/origins-plus-plus/issues"
authors = "TheQuantumXenon"
credits = "Credit goes to original authors (see CurseForge description)."
logoFile = "icon.png"

[[dependencies.origins_plus_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"

[[dependencies.origins_plus_plus]]
modId = "origins"
mandatory = true
versionRange = "[1.19.2-1.5.0.6,)"

[[dependencies.origins_plus_plus]]
modId = "pehkui"
mandatory = true
versionRange = "[3.4.0,)"

[[dependencies.origins_plus_plus]]
modId = "xlpackets"
mandatory = true
versionRange = "[1.18.2-2,)"

[[dependencies.origins_plus_plus]]
modId = "connectivity"
mandatory = true
versionRange = "[1.19.2-3.4,)"